### ISSUE TITLE
msgpack error with latest version of Metasploit from git

### ISSUE THREAD

**Issue by thesle3p** [rsmudge/armitage#184]
I have noticed that Armitage can't seem to initialize on the latest version of metasploit on Both Debian Jessie and Arch linux after a update of metasploit  to 93125a9 (the latest version as of this post) and  ruby msgpack version 0.6.0 the error message armitage loops is below: 
Warning: checkError(): java.lang.RuntimeException: org.msgpack.UnpackException: parse error at server.sl:453

**Comment by rsmudge** [comment]
Thanks for reporting this. I'm aware of the issue and I'm testing updated dependencies that fix whatever issue is present. I expect to push a fix after the MSF package on Kali Linux updates to require this gem.

**Comment by majk-p** [comment]
I also have this problem on OS X 10.10.3.

**Comment by thesle3p** [comment]
Is there a time frame as to when Kali is pushing the updated Package and when the update for Armitage is getting pushed? I also noticed this issue is also present in the Trial version of Cobalt Strike.......

**Comment by rsmudge** [comment]
When I push a package to address this issue, it'll go into Kali within 24 hours. I have a good relationship with the person who maintains the Armitage package.

**Comment by thesle3p** [comment]
Any chance of it being released a bit earlier on github or on fast and
easy hacking for those of us that don't use Kali?

**Comment by rsmudge** [comment]
The binaries will go to fastandeasyhacking.com at the same time the source code hits Github. Kali will follow shortly after.

**Comment by rsmudge** [comment]
It looks like the latest Metasploit stable package on Kali addresses these issues. No update is needed.

**Comment by thesle3p** [comment]
I can confirm this issue is still present with the Git version of
Metasploit on Both Arch Linux and Stock Debian Jessie, Looking on the
Kali pkg tracker they have not upgraded metasploit to run off of the
version of Msgpack to the version where this issue presents it's self.
I also checked and the Trial version of Cobalt Strike has the same issue
with the most up to date version of Metasploit on Arch Linux ( I only
have one trial so I can't confirm this issue is still there on Debian
Jessie with CS but I see no reason why it would not be).

**Comment by rsmudge** [comment]
Re: Armitage and Cobalt Strike

I support the latest stable Metasploit package available on Kali Linux. I also support the commit level noted in the releasenotes.txt file. Right now, neither of these supported environments are affected by this issue. I will address this issue, on my own timeline, to future proof these supported environments by a dependency shift that's coming. For now, you'll need to use a supported configuration.

-- Raphael

**Comment by thesle3p** [comment]
Ok, I found a temporary work around by editing gemfile.lock for MSF to
require msgpack version 0.5.12 and manually installing that gem, you
will however have to do that after every msfupdate. Thank you for your
time in this matter.

**Comment by Lutorio** [comment]
How did you do it?

**Comment by thesle3p** [comment]
Edit Gemfile.lock with your favorite text editor where it says:
 GEM
  remote: https://rubygems.org/
  specs:
msgpack (0.6.0)

 To say:
msgpack (0.5.12)

You will have to do this each time you run msfupdate

**Comment by darkoperator** [comment]
I'm getting the same error on yosemitie with the latest framework and latest build fromhttp://www.fastandeasyhacking.com/download/armitage-latest.tgz

**Comment by cimenli42** [comment]
i have same problem

Connecting to 127.0.0.1:55553
org.msgpack.UnpackException: parse error

**Comment by pamamolf** [comment]
I have the same problem also on Kali 2.0 

Connecting to 127.0.0.1:55553
org.msgpack.UnpackException: parse error

Any official fix for it?

**Comment by darkoperator** [comment]
Mudge is working on a fix, he is aware of the problem

**Comment by sandikast** [comment]
What a pity. Kali 2.0 also has this problem...
Connecting to 127.0.0.1:55553
 org.msgpack.UnpackException: parse error

**Comment by rsmudge** [comment]
This issue is fixed now. See commit: fd13d9f45ff738a4642706924d6d02e51dfcbbcc

**Comment by pamamolf** [comment]
What we have to do in Kali 2 to get that fix?

**Comment by persianate** [comment]
What we have to do in Kali 2 to get that fix? armitage
Connecting to 127.0.0.1:55553
org.msgpack.UnpackException: parse error

**Comment by persianate** [comment]
What we have to do in Kali 2 to get that fix? armitage
Connecting to 127.0.0.1:55553
org.msgpack.UnpackException: parse error

**Comment by prndown** [comment]
O que temos de fazer em Kali 2 para obter esse corrigir? Armitage 
Ligar a 127.0.0.1:55553 
org.msgpack.UnpackException: erro de análise

**Comment by Bhramanmonk** [comment]
I am having the same problem in Kali 2.0... any fix out yet??? What is causing this problem???

**Comment by darkoperator** [comment]
Once the bug id fixed it is up to the Kali team to package and push the update unless you want to build from source yourself and install by hand I believe.

**Comment by prndown** [comment]
armitage solve the problem opening. download http://www.fastandeasyhacking.com/download
and decompresses
tar -xf armitage150813.tgz
cd armitage
./armitage

**Comment by paoliniluis** [comment]
Issue solved and already pushed to the official repo. If an apt-get update does not show anything check if the sources in /etc/apt/sources.list are the same as in http://docs.kali.org/general-use/kali-linux-sources-list-repositories

**Comment by alliehanichak** [comment]
"armitage solve the problem opening. download http://www.fastandeasyhacking.com/download
and decompresses
tar -xf armitage150813.tgz
cd armitage
./armitage"
This worked!

**Comment by pirate** [comment]
I have a fresh install of MSF using the pkg: `4.16.5-dev-be66ed8af3c355b1280e1a2bdbe5dd1a74e7bc58`

I'm still having this problem with the latest [version](https://github.com/rsmudge/armitage/commit/c8ca6c00b5584444ef3c3a8e32341f43974567bd) of armitage from git (on macOS 10.12.6):
```bash
brew install ant
git clone https://github.com/rsmudge/armitage.git
cd armitage
ant compile
cd ./release/armitage-unix/
./armitage

[*] Starting msfrpcd for you.
Found a database at /Users/squash/.msf4/db, checking to see if it is started
Starting database at /Users/squash/.msf4/db...success
[*] MSGRPC starting on 127.0.0.1:55553 (NO SSL):Msg...
[*] MSGRPC ready at 2017-09-07 04:39:01 -0500.
```

<img width="476" alt="screen shot 2017-09-07 at 4 42 17 am" src="https://user-images.githubusercontent.com/511499/30157155-21421236-9387-11e7-8dd5-8e0fb12a9f7e.PNG">

`org.msgpack.UnpackException: parse error`
