### ISSUE TITLE
Can't see hosts from database

### ISSUE THREAD

**Issue by RasmusBeck** [rsmudge/armitage#191]
I'm having a bit of an issue getting up and running with Armitage. I am running the latest version of Kali Linux with Metasploit 4.11.12-dev (straight out of the box) and armitage 1.4.11. 

My issue is that after I run a scan, save it as an XML file by slapping on "-oX filename.xml" to the nMap command then try to import it I'm not seeing any hosts in the target window. I ran the "hosts" command from the console and I can see the target there. The target is a Metasploitable VM, so there should be no issues there.

I've been googling like hell and maybe I've missed something, but I can't seem to find a solution. I'm a fresh noob with Kali and pentesting in general, so I'm more likely than not doing something wrong. 

Any ideas?

**Comment by rsmudge** [comment]
Check your workspaces. Armitage is not compatible with Metasploit workspaces. If you're in anything other than default, that's your problem.

**Comment by RasmusBeck** [comment]
I'm in default.

**Comment by RasmusBeck** [comment]
rsmudge, I'm in default.
