### ISSUE TITLE
“The Parallel GC can not be combined with -XX:ParallelGCThreads=0.” on macOS

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [rsmudge/armitage#204]

**Comment by rsmudge** [comment]
https://blog.cobaltstrike.com/2017/04/26/java-startup-bug-in-java-1-8u131/

**Comment by ELLIOTTCABLE** [comment]
@rsmudge ahhah, I was aware — sorry, I hit return by accident before having typed up my Issue!

Point is, this isn't easy to fix on the user's end — basically, an end-user would have to unwrap the `.jar` from your `.app`-bundle, and use a command-line script to invoke it with custom arguments. (Also see: caskroom/homebrew-cask#34322)

**Comment by rsmudge** [comment]
This is a bug in an Armitage dependency. This is not an Armitage issue. I will take no action on this. A fix for this issue, in the dependency itself, will come.
