### ISSUE TITLE
The Parallel GC can not be combined with -XX:ParallelGCThreads=0

### ISSUE THREAD

**Issue by hayg97** [rsmudge/armitage#205]
Hello,
i am facing this problem when trying to run armitage, 
i've deleted the freamwork and re-install it again. But the problem didn't solve.
i did many searches and found that it's a bug.
can you please help me how to fix it 
and thanks
best regards
Haig

**Comment by rsmudge** [comment]
https://blog.cobaltstrike.com/2017/04/26/java-startup-bug-in-java-1-8u131/
