### ISSUE TITLE
20s delay before meterpreter commands return

### ISSUE THREAD

**Issue by PeterNerlich** [rsmudge/armitage#226]
In a demonstration setup, we have a physical laptop running up to date Kali (rolling), connected via a switch to another laptop running Win10 and finally, within a VirtualBox Win7. The virtual machine is set up with a bridge to the lan adapter.

Connecting to the victim system using meterpreter tcp works. Armitage however seems to need quite some thinking to execute meterpreter commands — whether from the embedded console or e.g. by listing directories. CPU and RAM don't show intensive activities, it just seems to idle. Working with msfconsole, the commands execute quickly as expected (<1s for `getuid`, while armitage needs 21s).

Can you help me debug this problem? I cloned this repo to put some old fashioned print statements in to debug where the most time is spent and dug around just a bit so far:
Apparently, from pressing [Enter] to the `MeterpreterSession.processCommand()` call alone two seconds pass. From there, the for loop is reached almost immediately, while the response is always delayed by ~20s. I followed through to `RpcConnectionImpl.exec()`, but didn't put time into understanding that and finding the code that then reports the result yet. But maybe this is already known, or you know only one place this could come from.

However, I don't know whether I'll be quickly called off this task in the following days, then I may not be able to properly help out.

**Comment by PeterNerlich** [comment]
For the record, I get the impression that this might not be a problem in armitage but in `msfrpcd`. I looked into their logs in `/root/.msf4/logs/framework.log`, and though there are errors, they do not occour when armitage issues commands but on startup of the server... I'm reluctant of opening an issue on rapid7/metasploit-framework though because I expect I will not be able to follow through after posting for more information etc.

**Comment by PeterNerlich** [comment]
This is a problem most likely introduced with metasploit-framework 5.x.x - we fixed it now by manually installing version 4.17.72, so I'll be closing this.

**Comment by TheShadow88** [comment]
Yes I have the same issue, currently with version 6.0.40 of metasploit. I notice at the start of armitage i can run commands relatively fine, but after maybe getting a meterpreter session or running a few commands i start receiving significant delay for any command or module i try to run.

I used the msgrpc plugin from metasploit and connected armitage to the server, and same as you - running commands from the normal terminal msf console was instant, while using any part of armitage that has to gather or send data from msf was very very slow. It leads me to believe that there is maybe some communication issue between armitage and the RPC server
